#!/usr/bin/python
#coding:utf-8
# Copyright (C) 2005-2016 All rights reserved.
# FILENAME: 	 app_conf.py
# VERSION: 	 1.0
# CREATED: 	 2016-02-23 13:39
# AUTHOR: 	 xuexiang
# DESCRIPTION:   应用配置
#                此表需与数据库一致。
#
# HISTORY: 
#*************************************************************

#自营PC官网价格采集
app_zygw_collect_id = 100

#淘宝抢购活动
app_tbhdqg_collect_id = 101

#天猫处方药列表页更新
app_tmfcy_listupdate_id = 102
